/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MobMiniV4.glb --transform 
Files: MobMiniV4.glb [835.55KB] > /Users/mattwright/ProjectsCode/mob-earman/public/assets/glb/MobMiniV4-transformed.glb [274.76KB] (67%)
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/MobMiniV4-transformed.glb"
  );

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="mini">
        <group name="eye" rotation={[1.505, -0.067, -3.129]} scale={0.269}>
          <mesh
            name="Sphere012"
            geometry={nodes.Sphere012.geometry}
            material={materials.eyePaper}
          />
          <mesh
            name="Sphere012_1"
            geometry={nodes.Sphere012_1.geometry}
            material={materials.eyePrimary}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/MobMiniV4-transformed.glb");
