/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mobV2.0.glb 
*/

import React, { useContext, useEffect, useMemo } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { ClipNameContext } from "../ClipNameContext";
import type { AnimationAction, Material } from "three";
import { ModeContext } from "../ModeContext";

export default function MobV2(props) {
  const group = React.useRef();
  const gltf = useGLTF("/assets/glb/mobV2.0.glb");
  const { scene, animations } = gltf;
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions, mixer } = useAnimations(animations, group);
  const clipName = useContext(ClipNameContext);
  const mode = useContext(ModeContext);
  //switch mode needs to take in the parameters of each item material then push them into the cases. So far we have 3
  const switchMode = (
    m1Paint: Material,
    m2Paper: Material,
    m3Primary: Material
  ): Material => {
    switch (mode) {
      case "paint":
        return m1Paint;
      case "paper":
        return m2Paper;
      case "primary":
        return m3Primary;
      default:
        return m1Paint;
    }
  };

  const cubeYellowMaterial = useMemo(() => {
    return switchMode(
      materials.cubeYellowPaint,
      materials.cubePaper,
      materials.cubeYellowPrimary
    );
  }, [mode]);

  const lilBombMaterial = useMemo(() => {
    console.log(mode);
    return switchMode(
      materials.lilBomb,
      materials.lilBombPaper,
      materials.lilBombPrimary
    );
  }, [mode]);

  const bigBlockMaterial = useMemo(() => {
    return switchMode(
      materials["Big Block"],
      materials.bigBlockPaper,
      materials.bigBlockPrimary
    );
  }, [mode]);

  /**
   * LOGIC FOR THE ANIMATIONS USING THE USE ANIMATIONS HOOK
   */ useEffect(() => {
    if (!mixer || !actions) return; //if there's no mixer or actions leave it

    const allActions = Object.values(actions).filter(
      Boolean
    ) as AnimationAction[];

    const actionFilter = (clipType: string) =>
      allActions.filter((a) => a.getClip().name.includes(clipType));

    const runningActions = allActions.filter((a) => a.isRunning());

    const nextClip = clipName!; //for some reason this won't play the giant paw animation if not imperative
    const nextActions = actionFilter(nextClip); //getting the next actions is just finding the clipName (string) in the actions

    const FADE_DURATION = 1;

    if (runningActions.length === 0) {
      nextActions.forEach((a) => a.reset().fadeIn(FADE_DURATION).play());
    } else {
      runningActions.forEach((a) => {
        a.fadeOut(FADE_DURATION);
      });

      nextActions.forEach((a) => {
        a.reset().fadeIn(FADE_DURATION).play();
      });
    }

    return () => {
      allActions.forEach((a) => a.fadeOut(0.2));
    };
  }, [actions, clipName, mixer]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="mob">
        <group
          name="controlEmpty"
          position={[0.384, 0.004, -0.18]}
          rotation={[0, 0.476, 0]}
          scale={0.033}
        >
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={switchMode(
              materials.cubePaint,
              materials.cubePaper,
              materials.cubeBluePrimary
            )}
            position={[-3.674, 1.795, 6.297]}
            rotation={[0.811, 0.792, -0.616]}
            scale={[-0.368, -1.684, -0.368]}
          />
          <mesh
            name="Cube007"
            geometry={nodes.Cube007.geometry}
            material={switchMode(
              materials.cubeYellowPaint,
              materials.cubePaper,
              materials.cubeYellowPrimary
            )}
            position={[-7.678, 0.899, 1.808]}
            rotation={[-2.52, -0.48, -2.96]}
            scale={0.359}
          />
          <mesh
            name="Cube014"
            geometry={nodes.Cube014.geometry}
            material={materials.bl}
            position={[6.879, 11.465, 3.975]}
            rotation={[2.513, -0.647, -0.887]}
            scale={2.291}
          />
        </group>
        <group
          name="hand"
          position={[0.593, 0.22, -0.35]}
          rotation={[0.293, 0.069, -0.634]}
          scale={0.014}
        >
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone002} />
          <primitive object={nodes.Bone005} />
          <primitive object={nodes.Bone008} />
        </group>
        <group
          name="GIANTPAWEMPTY"
          position={[0.916, 0.324, 0.096]}
          rotation={[0.598, 0.257, 0.448]}
          scale={0.042}
        >
          <group
            name="Armature"
            position={[-8.539, -2.495, 1.904]}
            rotation={[0.06, 0.198, -1.298]}
            scale={2.786}
          >
            <primitive object={nodes.Bone_1} />
            <skinnedMesh
              name="Cube003"
              geometry={nodes.Cube003.geometry}
              material={materials.giantPaw}
              skeleton={nodes.Cube003.skeleton}
            />
          </group>
          <group
            name="Armature001"
            position={[5.702, 2.162, -2.91]}
            rotation={[0.389, -0.118, -1.794]}
          >
            <primitive object={nodes.Bone_2} />
            <primitive object={nodes.Bone002_2} />
            <skinnedMesh
              name="Cube008"
              geometry={nodes.Cube008.geometry}
              material={materials.smallPaw}
              skeleton={nodes.Cube008.skeleton}
            />
            <skinnedMesh
              name="Cube010"
              geometry={nodes.Cube010.geometry}
              material={materials.cubeYellowPaint}
              skeleton={nodes.Cube010.skeleton}
            />
          </group>
          <mesh
            name="lilbomb2"
            geometry={nodes.lilbomb2.geometry}
            material={lilBombMaterial}
            position={[3.056, 3.816, 2.835]}
            rotation={[0.339, -0.541, -2.755]}
            scale={0.498}
          />
          <mesh
            name="lilbigbomb"
            geometry={nodes.lilbigbomb.geometry}
            material={lilBombMaterial}
            position={[-2.499, 2.317, -0.619]}
            rotation={[0.8, 0.306, -1.274]}
            scale={2.387}
          />
          <mesh
            name="Cube006"
            geometry={nodes.Cube006.geometry}
            material={materials.gem}
            position={[0.615, -1.322, 0.714]}
            rotation={[2.911, -0.023, -0.119]}
            scale={[2.777, 0.378, 0.378]}
          />
        </group>
        <mesh
          name="smallEye"
          geometry={nodes.smallEye.geometry}
          material={materials.eyePaint}
          position={[0.759, 0.19, -0.152]}
          rotation={[-0.057, -0.051, -1.394]}
          scale={0.033}
        />
        <mesh
          name="bigBlock"
          geometry={nodes.bigBlock.geometry}
          material={bigBlockMaterial}
          position={[-0.192, 0.538, -0.185]}
          rotation={[0.537, -0.102, 2.569]}
          scale={0.175}
        >
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials.cylinder}
            position={[-0.332, -0.345, 2.454]}
            rotation={[3.084, -0.066, 0.042]}
            scale={[-0.241, -2.579, -0.241]}
          />
        </mesh>
        <mesh
          name="EYE"
          geometry={nodes.EYE.geometry}
          material={materials.eyePaint}
          position={[0.565, 0.24, -0.252]}
          rotation={[1.546, 0.272, 1.356]}
          scale={0.046}
        />
        <mesh
          name="sharp4"
          geometry={nodes.sharp4.geometry}
          material={materials.bl}
          position={[0.477, 0.191, -0.184]}
          rotation={[0.348, 0.245, 2.526]}
          scale={0.033}
        />
        <mesh
          name="sharp5"
          geometry={nodes.sharp5.geometry}
          material={materials.bl}
          position={[0.702, 0.636, -0.035]}
          rotation={[0.746, 0.083, 2.245]}
          scale={0.093}
        />
        <mesh
          name="sharp6"
          geometry={nodes.sharp6.geometry}
          material={materials.bl}
          position={[0.565, 0.416, -0.362]}
          rotation={[0.304, -0.63, 2.656]}
          scale={0.136}
        />
        <mesh
          name="HALO"
          geometry={nodes.HALO.geometry}
          material={materials.EMISSION}
          position={[0.351, 0.249, -0.236]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.167}
        />
        <mesh
          name="plane1002"
          geometry={nodes.plane1002.geometry}
          material={materials.bl}
          position={[0.479, 0.476, -0.56]}
          rotation={[0.358, 0.265, 2.178]}
          scale={0.076}
        />
        <skinnedMesh
          name="Cube019"
          geometry={nodes.Cube019.geometry}
          material={materials.handPaint}
          skeleton={nodes.Cube019.skeleton}
          position={[0.593, 0.22, -0.35]}
          rotation={[0.293, 0.069, -0.634]}
          scale={0.014}
        />
      </group>
      <group name="TextureDork" scale={0.11} visible={false}>
        <mesh
          name="Cube005"
          geometry={nodes.Cube005.geometry}
          material={materials["Big Block"]}
        />
        <mesh
          name="Cube005_1"
          geometry={nodes.Cube005_1.geometry}
          material={materials.bigBlockPaper}
        />
        <mesh
          name="Cube005_2"
          geometry={nodes.Cube005_2.geometry}
          material={materials.bigBlockPrimary}
        />
        <mesh
          name="Cube005_3"
          geometry={nodes.Cube005_3.geometry}
          material={materials.cubeBluePrimary}
        />
        <mesh
          name="Cube005_4"
          geometry={nodes.Cube005_4.geometry}
          material={materials.cubePaper}
        />
        <mesh
          name="Cube005_5"
          geometry={nodes.Cube005_5.geometry}
          material={materials.cubeRedPrimary}
        />
        <mesh
          name="Cube005_6"
          geometry={nodes.Cube005_6.geometry}
          material={cubeYellowMaterial}
        />
        <mesh
          name="Cube005_7"
          geometry={nodes.Cube005_7.geometry}
          material={materials.cylinder}
        />
        <mesh
          name="Cube005_8"
          geometry={nodes.Cube005_8.geometry}
          material={materials.eyePaper}
        />
        <mesh
          name="Cube005_9"
          geometry={nodes.Cube005_9.geometry}
          material={materials.eyePaint}
        />
        <mesh
          name="Cube005_10"
          geometry={nodes.Cube005_10.geometry}
          material={materials.eyePrimary}
        />
        <mesh
          name="Cube005_11"
          geometry={nodes.Cube005_11.geometry}
          material={materials.gem}
        />
        <mesh
          name="Cube005_12"
          geometry={nodes.Cube005_12.geometry}
          material={materials.gemPaper}
        />
        <mesh
          name="Cube005_13"
          geometry={nodes.Cube005_13.geometry}
          material={materials.gemPrimary}
        />
        <mesh
          name="Cube005_14"
          geometry={nodes.Cube005_14.geometry}
          material={materials.giantPaw}
        />
        <mesh
          name="Cube005_15"
          geometry={nodes.Cube005_15.geometry}
          material={materials.giantPawPaper}
        />
        <mesh
          name="Cube005_16"
          geometry={nodes.Cube005_16.geometry}
          material={materials.giantPawPrimary}
        />
        <mesh
          name="Cube005_17"
          geometry={nodes.Cube005_17.geometry}
          material={materials.handPaint}
        />
        <mesh
          name="Cube005_18"
          geometry={nodes.Cube005_18.geometry}
          material={materials.handPaper}
        />
        <mesh
          name="Cube005_19"
          geometry={nodes.Cube005_19.geometry}
          material={materials.handPrimary}
        />
        <mesh
          name="Cube005_20"
          geometry={nodes.Cube005_20.geometry}
          material={materials.lilBomb}
        />
        <mesh
          name="Cube005_21"
          geometry={nodes.Cube005_21.geometry}
          material={materials.lilBombPaper}
        />
        <mesh
          name="Cube005_22"
          geometry={nodes.Cube005_22.geometry}
          material={materials.lilBombPrimary}
        />
        <mesh
          name="Cube005_23"
          geometry={nodes.Cube005_23.geometry}
          material={materials.cylinderPrimary}
        />
        <mesh
          name="Cube005_24"
          geometry={nodes.Cube005_24.geometry}
          material={materials.cubePaint}
        />
        <mesh
          name="Cube005_25"
          geometry={nodes.Cube005_25.geometry}
          material={materials.smallPaw}
        />
        <mesh
          name="Cube005_26"
          geometry={nodes.Cube005_26.geometry}
          material={materials.smallPawPaper}
        />
        <mesh
          name="Cube005_27"
          geometry={nodes.Cube005_27.geometry}
          material={materials.smallPawPrimary}
        />
        <mesh
          name="Cube005_28"
          geometry={nodes.Cube005_28.geometry}
          material={cubeYellowMaterial}
        />
        <mesh
          name="Cube005_29"
          geometry={nodes.Cube005_29.geometry}
          material={materials.cylinderPaper}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/glb/mobV2.0.glb");
