/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/glb/TEST3.glb 
*/

import React, { useEffect, useRef, useState } from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import * as THREE from "three";

export default function TEST3(props) {
  const group = React.useRef();
  const gltf = useGLTF("/assets/glb/TEST3.glb");
  console.dir(gltf);
  const { scene, animations } = gltf;
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  const [currentAction, setCurrentAction] = useState("Idle");
  console.dir(actions);

  useEffect(() => {
    const actionList = {
      idle: "Idle",
      checkout: "checkout",
    };

    const currentActions = Object.values(actions).filter((a) =>
      a?.getClip().name.includes(currentAction)
    );

    currentActions.forEach((a) => {
      if (a && currentAction.includes(actionList.checkout)) {
        console.log(a);
        a.reset().play();
        setTimeout(() => {
          a.stop();
          setCurrentAction(actionList.idle);
        }, 833);
      } else {
        currentActions.forEach((a) => {
          if (a) a.reset().play();
        });
      }
    });

    return () => {
      currentActions.forEach((a) => {
        if (a) {
          console.log(a);
          a.stop();
        }
      });
    };
  }, [actions, currentAction]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="mob">
        <group
          name="controlEmpty"
          position={[0.384, 0.004, -0.18]}
          rotation={[0, 0.476, 0]}
          scale={0.033}
        >
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials.cubePaper}
            position={[-3.674, 1.795, 6.297]}
            rotation={[0.811, 0.792, -0.616]}
            scale={[-0.368, -1.684, -0.368]}
          />
          <mesh
            name="Cube014"
            geometry={nodes.Cube014.geometry}
            material={materials.bl}
            position={[6.879, 11.465, 3.975]}
            rotation={[2.513, -0.647, -0.887]}
            scale={2.291}
          />
        </group>
        <group
          name="hand"
          position={[0.593, 0.22, -0.35]}
          rotation={[0.293, 0.069, -0.634]}
          scale={0.014}
        >
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone002} />
          <primitive object={nodes.Bone005} />
          <primitive object={nodes.Bone008} />
        </group>
        <group
          name="GIANTPAWEMPTY"
          position={[0.916, 0.324, 0.096]}
          rotation={[0.598, 0.257, 0.448]}
          scale={0.042}
        >
          <mesh
            name="lilbomb2"
            geometry={nodes.lilbomb2.geometry}
            material={materials.lilBombPaper}
            position={[3.056, 3.816, 2.835]}
            rotation={[0.339, -0.541, -2.755]}
            scale={0.498}
          />
          <mesh
            name="lilbigbomb"
            geometry={nodes.lilbigbomb.geometry}
            material={materials.lilBombPaper}
            position={[-2.499, 2.317, -0.619]}
            rotation={[0.8, 0.306, -1.274]}
            scale={2.387}
          />
          <mesh
            name="Cube009"
            geometry={nodes.Cube009.geometry}
            material={materials.smallPawPaper}
            position={[6.968, -3.51, 1.853]}
            rotation={[-0.669, -0.149, 0.099]}
            scale={0.641}
          />
          <skinnedMesh
            name="Cube006"
            geometry={nodes.Cube006.geometry}
            material={materials.gemPaper}
            skeleton={nodes.Cube006.skeleton}
          />
        </group>
        <group
          name="Armature"
          position={[0.665, 0.031, 0.078]}
          rotation={[0.562, 0.461, -0.832]}
          scale={0.118}
        >
          <primitive object={nodes.Bone_1} />
        </group>
        <group
          name="Armature001"
          position={[1.057, 0.572, 0.065]}
          rotation={[1.018, 0.292, -1.485]}
          scale={0.042}
        >
          <primitive object={nodes.Bone_2} />
          <primitive object={nodes.Bone002_2} />
        </group>
        <mesh
          name="smallEye"
          geometry={nodes.smallEye.geometry}
          material={materials.eyePaper}
          position={[0.759, 0.19, -0.152]}
          rotation={[-0.057, -0.051, -1.394]}
          scale={0.033}
        />
        <mesh
          name="bigBlock"
          geometry={nodes.bigBlock.geometry}
          material={materials.bigBlockPaper}
          position={[-0.192, 0.538, -0.185]}
          rotation={[0.537, -0.102, 2.569]}
          scale={0.175}
        >
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials.cylinderPaper}
            position={[-0.332, -0.345, 2.454]}
            rotation={[3.084, -0.066, 0.042]}
            scale={[-0.241, -2.579, -0.241]}
          />
        </mesh>
        <mesh
          name="EYE"
          geometry={nodes.EYE.geometry}
          material={materials.eyePaper}
          position={[0.565, 0.24, -0.252]}
          rotation={[1.546, 0.272, 1.356]}
          scale={0.046}
        />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials.bl}
          position={[0.528, 0.265, 0.128]}
          rotation={[0.952, -0.278, 0.065]}
          scale={[0.076, 0.076, 0.054]}
        />
        <mesh
          name="sharp4"
          geometry={nodes.sharp4.geometry}
          material={materials.bl}
          position={[0.477, 0.191, -0.184]}
          rotation={[0.348, 0.245, 2.526]}
          scale={0.033}
        />
        <mesh
          name="sharp5"
          geometry={nodes.sharp5.geometry}
          material={materials.bl}
          position={[0.702, 0.636, -0.035]}
          rotation={[0.746, 0.083, 2.245]}
          scale={0.093}
        />
        <mesh
          name="sharp6"
          geometry={nodes.sharp6.geometry}
          material={materials.bl}
          position={[0.565, 0.416, -0.362]}
          rotation={[0.304, -0.63, 2.656]}
          scale={0.136}
        />
        <mesh
          name="HALO"
          geometry={nodes.HALO.geometry}
          material={materials.EMISSION}
          position={[0.351, 0.249, -0.236]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.167}
        />
        <mesh
          name="plane1002"
          geometry={nodes.plane1002.geometry}
          material={materials.bl}
          position={[0.479, 0.476, -0.56]}
          rotation={[0.358, 0.265, 2.178]}
          scale={0.076}
        />
        <skinnedMesh
          name="Cube019"
          geometry={nodes.Cube019.geometry}
          material={materials.handPaper}
          skeleton={nodes.Cube019.skeleton}
          position={[0.593, 0.22, -0.35]}
          rotation={[0.293, 0.069, -0.634]}
          scale={0.014}
        />
        <skinnedMesh
          name="Cube003"
          geometry={nodes.Cube003.geometry}
          material={materials.giantPawPaper}
          skeleton={nodes.Cube003.skeleton}
          position={[0.665, 0.031, 0.078]}
          rotation={[0.562, 0.461, -0.832]}
          scale={0.118}
        />
        <skinnedMesh
          name="Cube008"
          geometry={nodes.Cube008.geometry}
          material={materials.smallPawPaper}
          skeleton={nodes.Cube008.skeleton}
          position={[1.057, 0.572, 0.065]}
          rotation={[1.018, 0.292, -1.485]}
          scale={0.042}
        />
        <skinnedMesh
          name="Cube010"
          geometry={nodes.Cube010.geometry}
          material={materials.cubePaper}
          skeleton={nodes.Cube010.skeleton}
          position={[1.057, 0.572, 0.065]}
          rotation={[1.018, 0.292, -1.485]}
          scale={0.042}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/glb/TEST3.glb");
