/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/glb/TEST4.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
const path = "/assets/glb/TEST4.glb";
export default function Model(props) {
  const path = "/assets/glb/TEST4.glb";
  const group = React.useRef();
  const { scene, animations } = useGLTF(path);
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="mob">
        <group
          name="Camera"
          position={[0.239, 0.311, 2.178]}
          rotation={[1.439, 0.017, -0.126]}
          scale={0.116}
        />
        <group
          name="controlEmpty"
          position={[-0.105, -0.238, -0.405]}
          rotation={[0, -0.414, 0]}
          scale={0.033}
        >
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials.cubePaint}
            position={[-3.674, 1.795, 6.297]}
            rotation={[0.811, 0.792, -0.616]}
            scale={[-0.368, -1.684, -0.368]}
          />
          <mesh
            name="Cube001"
            geometry={nodes.Cube001.geometry}
            material={materials.cubePaint}
            position={[-0.461, 5.11, -10.516]}
            rotation={[2.385, -0.6, -2.949]}
            scale={[0.094, 0.43, 0.094]}
          />
          <mesh
            name="Cube002"
            geometry={nodes.Cube002.geometry}
            material={materials.cubePaint}
            position={[-2.55, 0.445, -1.538]}
            rotation={[-2.717, -0.136, -0.692]}
            scale={[-0.247, -1.133, -0.247]}
          />
          <mesh
            name="Cube007"
            geometry={nodes.Cube007.geometry}
            material={materials.cubeYellowPaint}
            position={[-7.678, 0.899, 1.808]}
            rotation={[-2.52, -0.48, -2.96]}
            scale={0.359}
          />
          <mesh
            name="Cube014"
            geometry={nodes.Cube014.geometry}
            material={materials.bl}
            position={[6.879, 11.465, 3.975]}
            rotation={[2.513, -0.647, -0.887]}
            scale={2.291}
          />
        </group>
        <group
          name="Point"
          position={[0.744, 0.51, -0.451]}
          rotation={[0, -1.571, 0]}
          scale={0.014}
        />
        <group
          name="lilbomb"
          position={[-0.413, -0.09, -0.098]}
          rotation={[0.084, -0.634, 1.954]}
          scale={-0.071}
        />
        <group
          name="hand"
          position={[0.065, -0.022, -0.196]}
          rotation={[1.336, -1.27, 0.711]}
          scale={0.014}
        >
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone002} />
          <primitive object={nodes.Bone005} />
          <primitive object={nodes.Bone008} />
          <skinnedMesh
            name="Cube019"
            geometry={nodes.Cube019.geometry}
            material={materials.handPaint}
            skeleton={nodes.Cube019.skeleton}
          />
        </group>
        <group
          name="Area001"
          position={[0.679, 0.163, 0.174]}
          rotation={[0.328, -0.971, 1.331]}
          scale={0.273}
        />
        <group
          name="GIANTPAWEMPTY"
          position={[-0.364, 0.074, 0.125]}
          rotation={[1.06, -0.901, 1.575]}
          scale={0.042}
        >
          <group
            name="Armature"
            position={[-8.539, -2.495, 1.904]}
            rotation={[0.06, 0.198, -1.298]}
            scale={2.786}
          >
            <primitive object={nodes.Bone_1} />
            <skinnedMesh
              name="Cube003"
              geometry={nodes.Cube003.geometry}
              material={materials.giantPaw}
              skeleton={nodes.Cube003.skeleton}
            />
          </group>
          <group
            name="Armature001"
            position={[5.702, 2.162, -2.91]}
            rotation={[0.389, -0.118, -1.794]}
          >
            <primitive object={nodes.Bone_2} />
            <primitive object={nodes.Bone002_2} />
            <skinnedMesh
              name="Cube008"
              geometry={nodes.Cube008.geometry}
              material={materials.smallPaw}
              skeleton={nodes.Cube008.skeleton}
            />
            <skinnedMesh
              name="Cube010"
              geometry={nodes.Cube010.geometry}
              material={materials.cubeYellowPaint}
              skeleton={nodes.Cube010.skeleton}
            />
          </group>
          <mesh
            name="lilbigbomb"
            geometry={nodes.lilbigbomb.geometry}
            material={materials.lilBomb}
            position={[-1.161, 5.384, -1.724]}
            rotation={[1.029, -0.074, -1.497]}
            scale={2.387}
          />
          <mesh
            name="Cube006"
            geometry={nodes.Cube006.geometry}
            material={materials.gem}
            position={[0.615, -1.322, 0.714]}
            rotation={[2.911, -0.023, -0.119]}
            scale={[2.777, 0.378, 0.378]}
          />
          <mesh
            name="lilbomb2"
            geometry={nodes.lilbomb2.geometry}
            material={materials.lilBomb}
            position={[3.056, 3.816, 2.835]}
            rotation={[0.328, -0.444, 2.849]}
            scale={0.498}
          />
        </group>
        <mesh
          name="smallEye"
          geometry={nodes.smallEye.geometry}
          material={materials.eyePaint}
          position={[-0.133, -0.052, -0.03]}
          rotation={[-2.845, -0.967, 1.608]}
          scale={0.033}
        />
        <mesh
          name="bigBlock"
          geometry={nodes.bigBlock.geometry}
          material={materials["Big Block"]}
          position={[-0.104, 0.301, -0.98]}
          rotation={[1.779, -1.017, -1.94]}
          scale={0.175}
        >
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials.cylinder}
            position={[-0.374, -0.343, 2.514]}
            rotation={[3.084, -0.066, 0.042]}
            scale={[-0.241, -2.579, -0.241]}
          />
        </mesh>
        <mesh
          name="EYE"
          geometry={nodes.EYE.geometry}
          material={materials.eyePaint}
          position={[-0.033, -0.001, -0.224]}
          rotation={[1.319, -0.038, 2.995]}
          scale={0.046}
        />
        <mesh
          name="sharp4"
          geometry={nodes.sharp4.geometry}
          material={materials.bl}
          position={[-0.101, -0.051, -0.312]}
          rotation={[0.938, -1.149, -2.776]}
          scale={0.033}
        />
        <mesh
          name="sharp5"
          geometry={nodes.sharp5.geometry}
          material={materials.bl}
          position={[-0.25, 0.395, -0.087]}
          rotation={[1.94, -1.174, -1.769]}
          scale={0.093}
        />
        <mesh
          name="sharp6"
          geometry={nodes.sharp6.geometry}
          material={materials.bl}
          position={[0.086, 0.18, -0.225]}
          rotation={[2.744, -0.837, -0.963]}
          scale={0.136}
        />
        <mesh
          name="HALO"
          geometry={nodes.HALO.geometry}
          material={materials.EMISSION}
          position={[-0.049, 0.008, -0.438]}
          rotation={[Math.PI / 2, -1.571, 0]}
          scale={0.167}
        />
        <mesh
          name="Mountain2"
          geometry={nodes.Mountain2.geometry}
          material={materials.bl}
          position={[0.04, -0.27, -0.431]}
          rotation={[2.709, 0.978, 2.109]}
          scale={[0.904, 0.277, 0.318]}
        />
        <mesh
          name="mountain1"
          geometry={nodes.mountain1.geometry}
          material={materials.bl}
          position={[-0.055, -0.275, -0.413]}
          rotation={[0.355, 0.641, -2.097]}
          scale={[0.626, 0.192, 0.22]}
        />
        <mesh
          name="plane1002"
          geometry={nodes.plane1002.geometry}
          material={materials.bl}
          position={[0.275, 0.234, -0.31]}
          rotation={[0.326, -1.261, 2.74]}
          scale={0.076}
        />
        <mesh
          name="mountain1002"
          geometry={nodes.mountain1002.geometry}
          material={materials.bl}
          position={[-0.138, -0.317, -0.385]}
          rotation={[0.355, 0.641, -2.097]}
          scale={[0.286, 0.088, 0.101]}
        />
        <group
          name="TextureDork"
          position={[-0.285, -0.242, -0.789]}
          rotation={[0, -1.571, 0]}
          scale={0.11}
        >
          <mesh
            name="Cube005"
            geometry={nodes.Cube005.geometry}
            material={materials["Big Block"]}
          />
          <mesh
            name="Cube005_1"
            geometry={nodes.Cube005_1.geometry}
            material={materials.bigBlockPaper}
          />
          <mesh
            name="Cube005_2"
            geometry={nodes.Cube005_2.geometry}
            material={materials.bigBlockPrimary}
          />
          <mesh
            name="Cube005_3"
            geometry={nodes.Cube005_3.geometry}
            material={materials.cubeBluePrimary}
          />
          <mesh
            name="Cube005_4"
            geometry={nodes.Cube005_4.geometry}
            material={materials.cubePaper}
          />
          <mesh
            name="Cube005_5"
            geometry={nodes.Cube005_5.geometry}
            material={materials.cubeRedPrimary}
          />
          <mesh
            name="Cube005_6"
            geometry={nodes.Cube005_6.geometry}
            material={materials.cubeYellowPrimary}
          />
          <mesh
            name="Cube005_7"
            geometry={nodes.Cube005_7.geometry}
            material={materials.cylinder}
          />
          <mesh
            name="Cube005_8"
            geometry={nodes.Cube005_8.geometry}
            material={materials.cylinderPaper}
          />
          <mesh
            name="Cube005_9"
            geometry={nodes.Cube005_9.geometry}
            material={materials.eyePaper}
          />
          <mesh
            name="Cube005_10"
            geometry={nodes.Cube005_10.geometry}
            material={materials.eyePaint}
          />
          <mesh
            name="Cube005_11"
            geometry={nodes.Cube005_11.geometry}
            material={materials.eyePrimary}
          />
          <mesh
            name="Cube005_12"
            geometry={nodes.Cube005_12.geometry}
            material={materials.gem}
          />
          <mesh
            name="Cube005_13"
            geometry={nodes.Cube005_13.geometry}
            material={materials.gemPaper}
          />
          <mesh
            name="Cube005_14"
            geometry={nodes.Cube005_14.geometry}
            material={materials.gemPrimary}
          />
          <mesh
            name="Cube005_15"
            geometry={nodes.Cube005_15.geometry}
            material={materials.giantPaw}
          />
          <mesh
            name="Cube005_16"
            geometry={nodes.Cube005_16.geometry}
            material={materials.giantPawPaper}
          />
          <mesh
            name="Cube005_17"
            geometry={nodes.Cube005_17.geometry}
            material={materials.giantPawPrimary}
          />
          <mesh
            name="Cube005_18"
            geometry={nodes.Cube005_18.geometry}
            material={materials.handPaint}
          />
          <mesh
            name="Cube005_19"
            geometry={nodes.Cube005_19.geometry}
            material={materials.handPaper}
          />
          <mesh
            name="Cube005_20"
            geometry={nodes.Cube005_20.geometry}
            material={materials.handPrimary}
          />
          <mesh
            name="Cube005_21"
            geometry={nodes.Cube005_21.geometry}
            material={materials.lilBomb}
          />
          <mesh
            name="Cube005_22"
            geometry={nodes.Cube005_22.geometry}
            material={materials.lilBombPaper}
          />
          <mesh
            name="Cube005_23"
            geometry={nodes.Cube005_23.geometry}
            material={materials.lilBombPrimary}
          />
          <mesh
            name="Cube005_24"
            geometry={nodes.Cube005_24.geometry}
            material={materials.cylinderPrimary}
          />
          <mesh
            name="Cube005_25"
            geometry={nodes.Cube005_25.geometry}
            material={materials.cylinderPaper}
          />
          <mesh
            name="Cube005_26"
            geometry={nodes.Cube005_26.geometry}
            material={materials.cubePaint}
          />
          <mesh
            name="Cube005_27"
            geometry={nodes.Cube005_27.geometry}
            material={materials.smallPaw}
          />
          <mesh
            name="Cube005_28"
            geometry={nodes.Cube005_28.geometry}
            material={materials.smallPawPaper}
          />
          <mesh
            name="Cube005_29"
            geometry={nodes.Cube005_29.geometry}
            material={materials.smallPawPrimary}
          />
          <mesh
            name="Cube005_30"
            geometry={nodes.Cube005_30.geometry}
            material={materials.cubeYellowPaint}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(path);
