/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MobMini.glb --transform 
Files: MobMini.glb [17.11MB] > /Users/mattwright/ProjectsCode/mob-earman/public/assets/glb/MobMini-transformed.glb [3.21MB] (81%)
*/

import React, { useContext, useEffect, useMemo } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { ModeContext } from "../../ModeContext";
import type { Material } from "three";

export function MobMini(props) {
  const group = React.useRef(null);
  const { nodes, materials, animations } = useGLTF(
    "/assets/glb/MobMini-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  const mode = useContext(ModeContext);

  const switchMode = (
    m1Paint: Material,
    m2Paper: Material,
    m3Primary: Material
  ): Material => {
    switch (mode) {
      case "paint":
        return m1Paint;
      case "paper":
        return m2Paper;
      case "primary":
        return m3Primary;
      default:
        return m1Paint;
    }
  };

  const eyeMaterial = useMemo(() => {
    return switchMode(
      materials.eyePaint,
      materials.eyePaper,
      materials.eyePaint
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mode]);

  const gemMaterial = useMemo(() => {
    return switchMode(materials.gem, materials.gemPaper, materials.gemPrimary);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mode]);

  const lilBombMaterial = useMemo(() => {
    return switchMode(
      materials.lilBomb,
      materials.lilBombPaper,
      materials.lilBombPrimary
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mode]);

  useEffect(() => {
    Object.values(actions).forEach((a) => {
      if (a) a.reset().play();
    });
    return () => {
      Object.values(actions).forEach((a) => {
        if (a) a.stop();
      });
    };
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="mini">
        <group
          name="Armature005"
          position={[-0.001, 0.016, -0.403]}
          scale={0.266}
        >
          <group name="Bone">
            <mesh
              name="EYE002"
              geometry={nodes.EYE002.geometry}
              material={eyeMaterial}
              rotation={[1.505, -0.067, -3.129]}
              scale={0.172}
            />
          </group>
        </group>
        <group
          name="Empty003"
          position={[-0.001, 0.016, -0.403]}
          rotation={[0.071, 0.327, -2.67]}
          scale={0.109}
        >
          <mesh
            name="Cube007"
            geometry={nodes.Cube007.geometry}
            material={materials.bl}
            position={[-0.155, 0.013, 0.088]}
            rotation={[-0.644, -0.161, -1.7]}
            scale={0.137}
          />
        </group>
        <group name="Empty004" position={[0.001, 0.025, -0.403]} />
        <mesh
          name="HALO001"
          geometry={nodes.HALO001.geometry}
          material={materials.EMISSION}
          position={[0.008, 0.033, -0.615]}
          rotation={[-3.046, -1.465, 1.546]}
          scale={0.108}
        />
        <mesh
          name="lilbigbomb001"
          geometry={nodes.lilbigbomb001.geometry}
          material={lilBombMaterial}
          position={[0.088, -0.083, -0.17]}
          rotation={[-2.919, -0.864, -1.935]}
          scale={0.034}
        />
        <mesh
          name="Cube011"
          geometry={nodes.Cube011.geometry}
          material={gemMaterial}
          position={[-0.062, 0.072, -0.085]}
          rotation={[-0.069, 0.628, -0.082]}
          scale={0.434}
        />
        <mesh
          name="mountain1001"
          geometry={nodes.mountain1001.geometry}
          material={materials.bl}
          position={[0.044, -0.092, -0.768]}
          rotation={[2.554, -0.674, -2.282]}
          scale={[0.128, 0.039, 0.045]}
        />
        <group name="Cube003" position={[-0.001, 0.016, -0.403]} scale={0.01}>
          <mesh
            name="Cube034"
            geometry={nodes.Cube034.geometry}
            material={materials["Big Block.001"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/glb/MobMini-transformed.glb");
