/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MobMiniV3.glb --transform 
Files: MobMiniV3.glb [767.62KB] > /Users/mattwright/ProjectsCode/mob-earman/public/assets/glb/MobMiniV3-transformed.glb [270.93KB] (65%)
*/

import React, { useContext } from "react";
import { useGLTF } from "@react-three/drei";
import { ModeContext } from "../../ModeContext";

export function MobMini(props) {
  const group = React.useRef(null);
  const { nodes, materials } = useGLTF("/assets/glb/MobMiniV4-transformed.glb");
  const mode = useContext(ModeContext);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="mini">
        <group name="eye" rotation={[1.505, -0.067, -3.129]} scale={0.269}>
          <mesh
            name="Sphere012"
            geometry={nodes.Sphere012.geometry}
            material={materials.eyePaper}
          />
          <mesh
            name="Sphere012_1"
            geometry={nodes.Sphere012_1.geometry}
            material={
              mode === "paint" || mode === "primary"
                ? materials.eyePrimary
                : materials.eyePaper
            }
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("assets/glb/MobMiniV4-transformed.glb");
